#!/bin/sh
# Copyright (c) 2014 Shinpei Kato and Mikael Åsberg.
# All rights reserved. This program and the accompanying materials are 
# made available under the terms of the GNU Public License v3.0 which 
# accompanies this distribution, and is available at 
# http://www.gnu.org/licenses/gpl.htm

module="resch"
device="resch"
group="root"
mode="666"
version=$(uname -r)
userinc="/usr/include/resch"
kerninc="/usr/src/kernels/$version/include/resch"

# invoke insmod with all arguments we got
# and use a pathname, as newer modutils dont like in . by default
/sbin/insmod $module.ko $* || exit 1

# remove stale nodes 
rm -f /dev/${device}*

# make a node
major=$(awk "\$2==\"resch\" {print \$1}" /proc/devices)
mknod /dev/${device} c $major 0;
chgrp $group /dev/${device};
chmod $mode  /dev/${device};

# make include directories for Resch.
if [ ! -d $kerninc ]; then
	mkdir $kerninc
fi
if [ ! -d $userinc ]; then
	mkdir $userinc
fi

# copy header files.
cp -f ./api.h $userinc/api.h
chmod 644 $userinc/api.h
cp -f ./tvops.h $userinc/tvops.h
chmod 644 $userinc/tvops.h
cp -f ./core.h $kerninc/core.h
chmod 644 $kerninc/core.h
cp -f ./config.h $kerninc/config.h
chmod 644 $kerninc/config.h
cp -f ./tvops.h $kerninc/tvops.h
chmod 644 $kerninc/tvops.h
