#!/bin/sh
# Copyright (c) 2014 Shinpei Kato and Mikael Åsberg.
# All rights reserved. This program and the accompanying materials are 
# made available under the terms of the GNU Public License v3.0 which 
# accompanies this distribution, and is available at 
# http://www.gnu.org/licenses/gpl.htm

module="resch"
device="resch"
version="$(uname -r)"
kerninc="/usr/src/kernels/$version/include/resch"
userinc="/usr/include/resch"

# invoke rmmod with all arguments we got
/sbin/rmmod $module $*

# Remove stale nodes

rm -f /dev/${device}
rm -rf $kerninc
rm -rf $userinc
