# Copyright (c) 2014 Shinpei Kato and Mikael Åsberg.
# All rights reserved. This program and the accompanying materials are 
# made available under the terms of the GNU Public License v3.0 which 
# accompanies this distribution, and is available at 
# http://www.gnu.org/licenses/gpl.htm

lib='../../library/libresch.a'

all: 
	@gcc -o test_overhead test_overhead.c $(lib)

clean:
	rm -f  test_overhead *~
