/* 
 * Copyright (c) 2014 Shinpei Kato and Mikael Åsberg.
 * All rights reserved. This program and the accompanying materials are 
 * made available under the terms of the GNU Public License v3.0 which 
 * accompanies this distribution, and is available at 
 * http://www.gnu.org/licenses/gpl.htm
 */
#ifndef __CONFIG_H__
#define __CONFIG_H__
/* this is automatically generated by the .configure script. */
#define NR_RT_CPUS 1
#define NR_RT_TASKS 64
#define PID_MAX 32768
#define LOAD_BALANCE_ENABLED 0
#endif
