# Copyright (c) 2014 MDH.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the GNU Public License v3.0
# which accompanies this distribution, and is available at
# http://www.gnu.org/licenses/gpl.html

lib='/usr/lib/resch/libresch.a'

all: 
	@gcc -o rt_task1 rt_task1.c $(lib)
	@gcc -o rt_task2 rt_task2.c $(lib)
	@gcc -o rt_task3 rt_task3.c $(lib)
	@gcc -o rt_task4 rt_task4.c $(lib)
	@gcc -o rt_task5 rt_task5.c $(lib)
	@gcc -o rt_task6 rt_task6.c $(lib)
	@gcc -o rt_task7 rt_task7.c $(lib)
	@gcc -o rt_task8 rt_task8.c $(lib)

clean:
	rm -f  rt_task1 rt_task2 rt_task3 rt_task4 rt_task5 rt_task6 rt_task7 rt_task8 *~
